services:
  - type: web
    name: IrinaFitnessBot
    env: python
    plan: free
    runtime: python-3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --worker-class gthread --threads 1
